### ISSUE TITLE
❓ Question: Social badges section | Why do Youtube Subscribers and Views count become invalid?

### ISSUE THREAD

**Issue by everndah** [DenverCoder1/github-readme-youtube-cards#104]
### Description

I have noticed that there are specific moments when the Social badges section Youtube Subscribers and Views Count are Invalid (See Image below). However, when they become invalid I do not seen the same happening to your Subscribers and Views count in your READme.  I have seen that Invalid display for at least 2 people at the same time .

![invalid](https://user-images.githubusercontent.com/66929420/232475605-f41e5782-6bcf-4192-93bb-235226a453c7.png)

**Comment by DenverCoder1** [comment]
This is a question about Shields.io

Here is the related issue there - https://github.com/badges/shields/issues/8605

There is an issue with the quota being reached for number of requests.

**Comment by everndah** [comment]
Many thanks sir, understood.
