### ISSUE TITLE
🚀 Feature: Support for formatting titles as right-to-left text

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-cards#131]
### Description

In the best case scenario, it should automatically be able to determine whether the title text should be displayed left-to-right or right-to-left and format it as such, *without the use of a query parameter*. The lang query parameter cannot necessarily be relied on since videos with English titles probably should not be right-aligned.

A library or a simple RTL character count vs LTR character count could be used to determine which direction the title should be formatted in.

### Actual output

[https://ytcards.demolab.com/?id=dQw4w9WgXcQ&title=לורם%20איפסום%20דולור%20סיט%20אמט,%20קונסקטורר%20אדיפיסינג%20אלית&lang=he&timestamp=1693000000&max_title_lines=2&width=250&border_radius=5](https://ytcards.demolab.com/?id=dQw4w9WgXcQ&title=%D7%9C%D7%95%D7%A8%D7%9D%20%D7%90%D7%99%D7%A4%D7%A1%D7%95%D7%9D%20%D7%93%D7%95%D7%9C%D7%95%D7%A8%20%D7%A1%D7%99%D7%98%20%D7%90%D7%9E%D7%98,%20%D7%A7%D7%95%D7%A0%D7%A1%D7%A7%D7%98%D7%95%D7%A8%D7%A8%20%D7%90%D7%93%D7%99%D7%A4%D7%99%D7%A1%D7%99%D7%A0%D7%92%20%D7%90%D7%9C%D7%99%D7%AA&lang=he&timestamp=1693000000&max_title_lines=2&width=250&border_radius=5)

![image](https://github.com/DenverCoder1/github-readme-youtube-cards/assets/20955511/8275398c-7f05-4162-be22-1e78452c25f0)

### Expected output

![image](https://github.com/DenverCoder1/github-readme-youtube-cards/assets/20955511/b75cca74-45e7-4e5e-b27a-fc2452b0fae7)

```svg
<g xmlns="http://www.w3.org/2000/svg" transform="translate(240, 150)">
    <text fill="#ffffff" font-family="Roboto, Segoe UI, Ubuntu, Arial, sans-serif" font-weight="600" font-size="15px" direction="rtl">
        <tspan x="0" dy="20px">לורם איפסום דולור סיט אמט,</tspan>
        <tspan x="0" dy="20px">קונסקטורר אדיפיסינג אלית</tspan>
    </text>
</g>
```

The x offset should be `{{ width - 10 if rtl_title else 10 }}`. The direction of the text should be set to `{{ 'rtl' if rtl_title else 'ltr' }}`.

`rtl_title` is a made up variable that will need to be created based on the direction of the title text (not the same as the existing `rtl` which is for the stats)

**Comment by Vyvy-vi** [comment]
I would really like to work on this issue

**Comment by DenverCoder1** [comment]
@Vyvy-vi Great! Feel free to let me know if you have any questions :smile:
