### ISSUE TITLE
🚀 Feature: HTML syntax output option

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-cards#24]
### Idea

Add option to update readme with HTML syntax instead of markdown syntax.

This can be useful if the user wants to take advantage of certain other HTML features such as wrapping the block in `<p align="center"></p>`.

### Solution

An option can be added, for example  `output_type: "markdown"` vs `output_type: "html"`.

Conditionally, if this option is set to "html", an HTML syntax should be returned instead.
```py
html_escaped_title = params["title"].replace('"', "&quot;")
return f'<a href="{video["link"]}"><img src="{self._base_url}?{urllib.parse.urlencode(params)}" alt="{html_escaped_title}" title="{html_escaped_title}"></a>'
```
For light mode / dark mode theme contexts, something like the following can be used (see https://github.blog/changelog/2022-05-19-specify-theme-context-for-images-in-markdown-beta/)
```py
return (
    f'<a href="{video["link"]}">\n'
    f"  <picture>\n"
    f'    <source media="(prefers-color-scheme: dark)" srcset="{self._base_url}?{urllib.parse.urlencode(dark_params)}">\n'
    f'    <img src="{self._base_url}?{urllib.parse.urlencode(light_params)}" alt="{html_escaped_title}" title="{html_escaped_title}">\n'
    "  </picture>\n"
    "</a>"
)
```

The default behavior should remain as markdown.

**Comment by Vyvy-vi** [comment]
I'd like to work on this.

**Comment by DenverCoder1** [comment]
@Vyvy-vi Great!

**Comment by DenverCoder1** [comment]
Any updates on this issue?
