### ISSUE TITLE
Idea: Use custom locale for "views" and date formats

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-cards#27]
Currently the cards display in English ("xx views", "2 days ago", etc."). It may be nice to translate the word "views" into multiple languages and find a way to display the relative time difference in multiple languages.

The JSON found at https://github.com/unicode-org/cldr-json/tree/main/cldr-json/cldr-dates-modern may be useful for the relative time differences.

An external library such as [humanize](https://pypi.org/project/humanize/) may also potentially help, but does not support as many locales.

Translations for the word "views" can be maintained independently (some examples can be found here: [QuickStats.i18n.php](https://github.com/Wikia/app/blob/75ee0d4413f4c0346cb67c91d5d281451d62d371/extensions/wikia/AdminDashboard/QuickStats.i18n.php), but we only need the word "views" and implemented in Python to make it easily accessible to the website code.

**Comment by Vyvy-vi** [comment]
I'd like to work on this issue. For the translations, would some library that supports plugins like crowdin be preferable, or could this be maintained with a python/JSON file stored in the project?
