### ISSUE TITLE
🚀 Feature: Allow the title to use two lines instead of just one

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-cards#28]
On YouTube, short titles can end up using only one line and moving the stats higher up, whereas longer titles can use up to two full lines (trimming occurs at the end of the second line).

Instead of only showing the first line, show a second line if the title is long enough and only trim after approximately the amount of characters in 2 lines of text.

Note: This can be a configurable option, for example `max_title_lines` defaulting to 1 to avoid making breaking changes.

![image](https://user-images.githubusercontent.com/20955511/189550853-56c810d8-0d1f-4401-ab8d-77e2e1c47b6c.png)

**Comment by Yugal41735** [comment]
Hey, I want to try to contribute for the above issue, could u kind of give me heads up on how can i get started on working on it.

**Comment by DenverCoder1** [comment]
Hi @Yugal41735, any updates? Are you still interested in contributing to the issue?

**Comment by Yugal41735** [comment]
recently done with my midsem, gonna start working on it.

**Comment by DenverCoder1** [comment]
@Yugal41735 Sorry for bugging you, but are you still working on it? Feel free to let me know if you need more time or if you'd like someone else to do it.

**Comment by Yugal41735** [comment]
kind of need a bit more time

**Comment by DenverCoder1** [comment]
@Yugal41735 Hi again, do you still plan to work on this feature?

**Comment by Yugal41735** [comment]
Would try to complete it by july, if unable to do so by end of month, then you could assign it to someone else. Sorry for taking so much long.
