### ISSUE TITLE
thumbnails are missing

### ISSUE THREAD

**Issue by FDiskas** [DenverCoder1/github-readme-youtube-cards#32]
Generated markdown are with broken video images

**Comment by DenverCoder1** [comment]
It's giving a 404 right now, probably because of the Render.com hosting which has been noticeably slow and unreliable.

I'm looking for ways to fix it but it's not really getting anywhere yet.

I think I'll try moving it to another host soon or at some point.

**Comment by DenverCoder1** [comment]
Sorry for the downtime. Render is still not working for me. I'm trying to move the hosting, but updating the CNAME records can take a few hours to take effect.

**Comment by DenverCoder1** [comment]
As a temporary workaround, you can try setting the `base_url` to `https://ytcards.vercel.app/`.

Eventually ytcards.demolab.com will point to that domain, but this can take several hours to complete.

Once the DNS is fully propogated, it is recommended to use demolab as it will be more flexible if host changes are needed in the future.

**Comment by FDiskas** [comment]
What about accessing images directly?


`https://i.ytimg.com/vi/<--Video ID-->/default.jpg`
[Image](https://i.ytimg.com/vi/WRVsOCh907o/default.jpg) Size Weight 120px Height 90px

`https://i.ytimg.com/vi/<--Video ID-->/mqdefault.jpg`
[Image](https://i.ytimg.com/vi/WRVsOCh907o/mqdefault.jpg) Size Weight 320px Height 180px

`https://i.ytimg.com/vi/<--Video ID-->/hqdefault.jpg`
[Image](https://i.ytimg.com/vi/WRVsOCh907o/sddefault.jpg) Size Weight 480px Height 360px

`https://i.ytimg.com/vi/<--Video ID-->/sddefault.jpg`
[Image](https://i.ytimg.com/vi/WRVsOCh907o/maxresdefault.jpg) Size Weight 640px Height 480px

`https://i.ytimg.com/vi/<--Video ID-->/maxresdefault.jpg`
[Image](https://i.ytimg.com/vi/WRVsOCh907o/maxresdefault.jpg) Size Weight 1280px Height 720px

**Comment by DenverCoder1** [comment]
The thumbnail is only part of the YouTube cards, the image also includes the duration, title, number of views, and relative time ago it was published dynamically

**Comment by DenverCoder1** [comment]
Should be temporarily fixed by #35 (temporarily made https://ytcards.vercel.app/ the default base url.

Will hopefully be changed back to demolab when that's working.

If you make a new workflow run, it should update and work correctly.

**Comment by DenverCoder1** [comment]
There were some configuration issues that needed to be resolved and it should be working on demolab also, as it used to.
(Now using Vercel as a host instead of Render)
