### ISSUE TITLE
Implement recommended community standards to the project

### ISSUE THREAD

**Issue by orama254** [DenverCoder1/github-readme-youtube-cards#34]
Hello @DenverCoder1 

I was going though this project and noticed that there are some missing items based on the [Github Community Standards recommendations](https://github.com/DenverCoder1/github-readme-youtube-cards/community) that would make the project contributor friendly, e.g. a code of conduct, a contributing guide file, an issue template and a pull request template.

Let me know if this is something you would like to implement on this project.

**Comment by ChinmayMhatre** [comment]
I could work on adding the templates.

**Comment by DenverCoder1** [comment]
Sure, I have some other projects with these files that the ones for this project can be based on

https://github.com/DenverCoder1/github-readme-streak-stats  
https://github.com/DenverCoder1/readme-typing-svg  
 https://github.com/DenverCoder1/custom-icon-badges

Of course as this is a Python project, some things will be different.

As far as contributing and testing instructions, there is some info at the end of the readme currently that could be used.

**Comment by ChinmayMhatre** [comment]
Hey @DenverCoder1 , Would you want the user to be able to make a blank issue template?

**Comment by ChinmayMhatre** [comment]
In addition to those maybe a template for documentation changes?

**Comment by DenverCoder1** [comment]
Sure, if you'd like
