### ISSUE TITLE
🐛 Bug: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/github-readme-youtube-cards#83]
### Description

> **Warning**
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix the above error by not using `set-output`.

Based on the link above, the following seems to be the alternative.

```diff
- echo "::set-output name=markdown::$(echo $UPDATE)"
+ echo "markdown=$(echo $UPDATE)" >> $GITHUB_OUTPUT
```

### Steps to reproduce

Happens on every workflow run

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by DenverCoder1** [comment]
@Vyvy-vi Great, thanks!

**Comment by DenverCoder1** [comment]
Deadline for this before set-ouput is disabled is May 31, 2023
